# Generated by Django 5.2.7 on 2025-11-04 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField()),
                ('parts_used', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_works', to=settings.AUTH_USER_MODEL)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='services.serviceorder')),
            ],
            options={
                'verbose_name': 'Service Work',
                'verbose_name_plural': 'Service Works',
                'ordering': ['-performed_at'],
            },
        ),
    ]
