# Generated by Django 5.2.7 on 2025-11-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='condition',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='warranty_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
