# Generated by Django 5.2.7 on 2025-11-03 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_condition_device_notes_device_purchase_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_type', models.CharField(choices=[('CPU', 'Processor'), ('RAM', 'RAM'), ('STORAGE', 'Storage'), ('SCREEN', 'Screen Size'), ('COLOR', 'Color'), ('OS', 'Operating System'), ('OTHER', 'Other')], max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='devices.device')),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specifications',
                'ordering': ['spec_type'],
            },
        ),
    ]
